import hashlib
import time
from typing import Any

from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad
from gmpy2 import mpz  # ty: ignore[unresolved-import]
from tqdm import tqdm

from .b64utils import base64_to_byte_str


def decrypt_secret(enc_package: dict[str, Any], logging: bool = True) -> bytes:
	"""
	Given a dictionary which was generated by encrypt_secret(), decrypt_secret() decrypts it and returns the secret as a byte string.
	If `logging` (defaults to True) is set to True, a progress bar is printed, along with extra debug information.
	"""
	base = enc_package["base"]
	modulus = enc_package["modulus"]
	iterations = enc_package["iterations"]
	secret_iv = base64_to_byte_str(enc_package["secret_iv"])
	encrypted_secret = base64_to_byte_str(enc_package["encrypted_secret"])
	key_iv = base64_to_byte_str(enc_package["key_iv"])
	encrypted_key = base64_to_byte_str(enc_package["encrypted_key"])

	# Compute puzzle result r via repeated modular squaring (gmpy2/GMP for speed)
	if logging:
		print("Unlocking encryption key...")
	start_time = time.time()
	r = mpz(base)
	n = mpz(modulus)
	if logging:
		# Update the progress bar in coarse chunks so tqdm's per-iteration cost
		# does not slow the hot loop. Otherwise decryption runs measurably longer
		# than the --time estimate, whose benchmark loop is uninstrumented.
		chunk = max(1, iterations // 1000)
		remaining = iterations
		with tqdm(total=iterations, desc="Unlocking", unit="iters") as bar:
			while remaining > 0:
				step = min(chunk, remaining)
				for _ in range(step):
					r = (r * r) % n
				remaining -= step
				bar.update(step)
	else:
		for _ in range(iterations):
			r = (r * r) % n
	r = int(r)
	end_time = time.time()
	if logging:
		print(f"Completed in {end_time - start_time:.2f} seconds")

	# Derive AES key from r
	if logging:
		print("Deriving AES key...")
	derived_key = hashlib.sha256(str(r).encode()).digest()[:16]

	# Decrypt AES key
	if logging:
		print("Decrypting AES key...")
	cipher2 = AES.new(derived_key, AES.MODE_CBC, iv=key_iv)
	aes_key = unpad(cipher2.decrypt(encrypted_key), AES.block_size)

	# Decrypt secret
	if logging:
		print("Decrypting secret...")
	cipher = AES.new(aes_key, AES.MODE_CBC, iv=secret_iv)
	secret = unpad(cipher.decrypt(encrypted_secret), AES.block_size)
	return secret
